# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gamm/Dev/StrayGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gamm/Dev/StrayGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gamm/Dev/StrayGL/CMakeFiles /home/gamm/Dev/StrayGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gamm/Dev/StrayGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StrayGL

# Build rule for target.
StrayGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StrayGL
.PHONY : StrayGL

# fast build rule for target.
StrayGL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/build
.PHONY : StrayGL/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f 3thparty/GLFW/CMakeFiles/uninstall.dir/build.make 3thparty/GLFW/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f 3thparty/GLFW/src/CMakeFiles/glfw.dir/build.make 3thparty/GLFW/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f 3thparty/GLFW/src/CMakeFiles/update_mappings.dir/build.make 3thparty/GLFW/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named StrayGL_BasicExample

# Build rule for target.
StrayGL_BasicExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StrayGL_BasicExample
.PHONY : StrayGL_BasicExample

# fast build rule for target.
StrayGL_BasicExample/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/StrayGL_BasicExample.dir/build.make examples/CMakeFiles/StrayGL_BasicExample.dir/build
.PHONY : StrayGL_BasicExample/fast

3thparty/GLAD/src/glad.o: 3thparty/GLAD/src/glad.c.o
.PHONY : 3thparty/GLAD/src/glad.o

# target to build an object file
3thparty/GLAD/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/3thparty/GLAD/src/glad.c.o
.PHONY : 3thparty/GLAD/src/glad.c.o

3thparty/GLAD/src/glad.i: 3thparty/GLAD/src/glad.c.i
.PHONY : 3thparty/GLAD/src/glad.i

# target to preprocess a source file
3thparty/GLAD/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/3thparty/GLAD/src/glad.c.i
.PHONY : 3thparty/GLAD/src/glad.c.i

3thparty/GLAD/src/glad.s: 3thparty/GLAD/src/glad.c.s
.PHONY : 3thparty/GLAD/src/glad.s

# target to generate assembly for a file
3thparty/GLAD/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/3thparty/GLAD/src/glad.c.s
.PHONY : 3thparty/GLAD/src/glad.c.s

3thparty/IMGUI/backends/imgui_impl_glfw.o: 3thparty/IMGUI/backends/imgui_impl_glfw.cpp.o
.PHONY : 3thparty/IMGUI/backends/imgui_impl_glfw.o

# target to build an object file
3thparty/IMGUI/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/backends/imgui_impl_glfw.cpp.o
.PHONY : 3thparty/IMGUI/backends/imgui_impl_glfw.cpp.o

3thparty/IMGUI/backends/imgui_impl_glfw.i: 3thparty/IMGUI/backends/imgui_impl_glfw.cpp.i
.PHONY : 3thparty/IMGUI/backends/imgui_impl_glfw.i

# target to preprocess a source file
3thparty/IMGUI/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/backends/imgui_impl_glfw.cpp.i
.PHONY : 3thparty/IMGUI/backends/imgui_impl_glfw.cpp.i

3thparty/IMGUI/backends/imgui_impl_glfw.s: 3thparty/IMGUI/backends/imgui_impl_glfw.cpp.s
.PHONY : 3thparty/IMGUI/backends/imgui_impl_glfw.s

# target to generate assembly for a file
3thparty/IMGUI/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/backends/imgui_impl_glfw.cpp.s
.PHONY : 3thparty/IMGUI/backends/imgui_impl_glfw.cpp.s

3thparty/IMGUI/backends/imgui_impl_opengl3.o: 3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.o
.PHONY : 3thparty/IMGUI/backends/imgui_impl_opengl3.o

# target to build an object file
3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.o
.PHONY : 3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.o

3thparty/IMGUI/backends/imgui_impl_opengl3.i: 3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.i
.PHONY : 3thparty/IMGUI/backends/imgui_impl_opengl3.i

# target to preprocess a source file
3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.i
.PHONY : 3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.i

3thparty/IMGUI/backends/imgui_impl_opengl3.s: 3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.s
.PHONY : 3thparty/IMGUI/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.s
.PHONY : 3thparty/IMGUI/backends/imgui_impl_opengl3.cpp.s

3thparty/IMGUI/imgui.o: 3thparty/IMGUI/imgui.cpp.o
.PHONY : 3thparty/IMGUI/imgui.o

# target to build an object file
3thparty/IMGUI/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui.cpp.o
.PHONY : 3thparty/IMGUI/imgui.cpp.o

3thparty/IMGUI/imgui.i: 3thparty/IMGUI/imgui.cpp.i
.PHONY : 3thparty/IMGUI/imgui.i

# target to preprocess a source file
3thparty/IMGUI/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui.cpp.i
.PHONY : 3thparty/IMGUI/imgui.cpp.i

3thparty/IMGUI/imgui.s: 3thparty/IMGUI/imgui.cpp.s
.PHONY : 3thparty/IMGUI/imgui.s

# target to generate assembly for a file
3thparty/IMGUI/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui.cpp.s
.PHONY : 3thparty/IMGUI/imgui.cpp.s

3thparty/IMGUI/imgui_draw.o: 3thparty/IMGUI/imgui_draw.cpp.o
.PHONY : 3thparty/IMGUI/imgui_draw.o

# target to build an object file
3thparty/IMGUI/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_draw.cpp.o
.PHONY : 3thparty/IMGUI/imgui_draw.cpp.o

3thparty/IMGUI/imgui_draw.i: 3thparty/IMGUI/imgui_draw.cpp.i
.PHONY : 3thparty/IMGUI/imgui_draw.i

# target to preprocess a source file
3thparty/IMGUI/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_draw.cpp.i
.PHONY : 3thparty/IMGUI/imgui_draw.cpp.i

3thparty/IMGUI/imgui_draw.s: 3thparty/IMGUI/imgui_draw.cpp.s
.PHONY : 3thparty/IMGUI/imgui_draw.s

# target to generate assembly for a file
3thparty/IMGUI/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_draw.cpp.s
.PHONY : 3thparty/IMGUI/imgui_draw.cpp.s

3thparty/IMGUI/imgui_tables.o: 3thparty/IMGUI/imgui_tables.cpp.o
.PHONY : 3thparty/IMGUI/imgui_tables.o

# target to build an object file
3thparty/IMGUI/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_tables.cpp.o
.PHONY : 3thparty/IMGUI/imgui_tables.cpp.o

3thparty/IMGUI/imgui_tables.i: 3thparty/IMGUI/imgui_tables.cpp.i
.PHONY : 3thparty/IMGUI/imgui_tables.i

# target to preprocess a source file
3thparty/IMGUI/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_tables.cpp.i
.PHONY : 3thparty/IMGUI/imgui_tables.cpp.i

3thparty/IMGUI/imgui_tables.s: 3thparty/IMGUI/imgui_tables.cpp.s
.PHONY : 3thparty/IMGUI/imgui_tables.s

# target to generate assembly for a file
3thparty/IMGUI/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_tables.cpp.s
.PHONY : 3thparty/IMGUI/imgui_tables.cpp.s

3thparty/IMGUI/imgui_widgets.o: 3thparty/IMGUI/imgui_widgets.cpp.o
.PHONY : 3thparty/IMGUI/imgui_widgets.o

# target to build an object file
3thparty/IMGUI/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_widgets.cpp.o
.PHONY : 3thparty/IMGUI/imgui_widgets.cpp.o

3thparty/IMGUI/imgui_widgets.i: 3thparty/IMGUI/imgui_widgets.cpp.i
.PHONY : 3thparty/IMGUI/imgui_widgets.i

# target to preprocess a source file
3thparty/IMGUI/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_widgets.cpp.i
.PHONY : 3thparty/IMGUI/imgui_widgets.cpp.i

3thparty/IMGUI/imgui_widgets.s: 3thparty/IMGUI/imgui_widgets.cpp.s
.PHONY : 3thparty/IMGUI/imgui_widgets.s

# target to generate assembly for a file
3thparty/IMGUI/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3thparty/IMGUI/imgui_widgets.cpp.s
.PHONY : 3thparty/IMGUI/imgui_widgets.cpp.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StrayGL.dir/build.make CMakeFiles/StrayGL.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... StrayGL"
	@echo "... StrayGL_BasicExample"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... 3thparty/GLAD/src/glad.o"
	@echo "... 3thparty/GLAD/src/glad.i"
	@echo "... 3thparty/GLAD/src/glad.s"
	@echo "... 3thparty/IMGUI/backends/imgui_impl_glfw.o"
	@echo "... 3thparty/IMGUI/backends/imgui_impl_glfw.i"
	@echo "... 3thparty/IMGUI/backends/imgui_impl_glfw.s"
	@echo "... 3thparty/IMGUI/backends/imgui_impl_opengl3.o"
	@echo "... 3thparty/IMGUI/backends/imgui_impl_opengl3.i"
	@echo "... 3thparty/IMGUI/backends/imgui_impl_opengl3.s"
	@echo "... 3thparty/IMGUI/imgui.o"
	@echo "... 3thparty/IMGUI/imgui.i"
	@echo "... 3thparty/IMGUI/imgui.s"
	@echo "... 3thparty/IMGUI/imgui_draw.o"
	@echo "... 3thparty/IMGUI/imgui_draw.i"
	@echo "... 3thparty/IMGUI/imgui_draw.s"
	@echo "... 3thparty/IMGUI/imgui_tables.o"
	@echo "... 3thparty/IMGUI/imgui_tables.i"
	@echo "... 3thparty/IMGUI/imgui_tables.s"
	@echo "... 3thparty/IMGUI/imgui_widgets.o"
	@echo "... 3thparty/IMGUI/imgui_widgets.i"
	@echo "... 3thparty/IMGUI/imgui_widgets.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

